name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.8.0+47

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  connectivity: ^0.4.5+2
  dio: ^3.0.3
  flutter_mailer: ^0.4.1+2
  flutter_web_browser: ^0.11.0
  launch_review: ^2.0.0

  ## Widgets
  add_2_calendar: ^1.3.0
  expand_widget: ^0.2.0+2
  flutter_local_notifications: ^0.8.4
  flutter_map: ^0.7.3
  flutter_markdown: ^0.3.0
  flutter_swiper: ^1.1.6
  row_collection: ^0.2.4
  sliver_fab: ^1.0.0

  ## Tools
  flutter_i18n: ^0.7.0
  package_info: ^0.4.0+10
  provider: ^3.1.0+1
  quick_actions: ^0.3.2+2
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+1
  system_setting: ^0.1.3

  ## Icons
  font_awesome_flutter: ^8.5.0

  ## Linter
  lint: ^0.3.2+dart205

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.3

flutter_native_splash:
  image: assets/icons/app.png
  color: "#151515"

flutter_icons:
  image_path: assets/icons/icon.png
  ios: true

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf

  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true
