name: cherry
description: SpaceX app made with Flutter.

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  http: 0.11.3+16
  intl: "^0.15.6"
  url_launcher: "^3.0.2"
  bubble_tab_indicator: "^0.1.2"
  flutter_custom_tabs: "^0.2.0"

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-Italic.ttf
        - asset: fonts/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Thin.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Italic.ttf
        - asset: fonts/ProductSans-Regular.ttf
          weight: 700

  uses-material-design: true